server:
  port: 8080
spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  datasource:
    url: jdbc:mysql://localhost:3307/ebnelhaythem_db
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: ebnelhaythem
jwt:
  secret: SecretKeyToGenJWTs
  expirationDateInMs: 864000000
logstash:
  host: localhost
  port: 5000