server:
  port: 6868
spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
      #ddl-auto: update
  datasource:
    #   url: jdbc:mysql://localhost:3306/ebnelhaythem
    url: jdbc:mysql://localhost:3307/ebnelhaythem_db
    username: root
    #password: test
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver